name: Terraform (apply)

on:
  push:
    branches:
      - "main"
    path:
      - "**.tf"
      - ".terraform.lock.hcl"
  workflow_dispatch:

jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          terraform_version: 1.5.6

      - run: terraform init
        working-directory: "./cloudflare-dns"

      - name: plan
        run: terraform plan -input=false -no-color -lock-timeout=10m
        id: tfplan
        working-directory: "./cloudflare-dns"
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: apply
        run: terraform apply -input=false -no-color -auto-approve -lock-timeout=10m
        working-directory: "./cloudflare-dns"
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
